name: CleanWorkFlow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4.2.1

     - name: Setup Java JDK
       uses: actions/setup-java@v4.4.0
       with:
          distribution: 'temurin'
          java-version: '17'

     - name: Run Tests with Gradle
       run: ./gradlew test

     - name: Make Gradle executable
       run: chmod +x ./gradlew
     - name: Build Release APK
       run: ./gradlew assembleRelease

     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4.4.3
       with:
         name: Android.apk
         path: app/build/outputs/apk/release/app-release.apk
