name: CleanWorkFlow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
     - uses: actions/checkout@v4.2.1
     - name: Setup Java JDK
     - uses: actions/setup-java@v4.4.0
       with:
          distribution: 'temurin'
          java-version: '1.8'
     - name: gradle
     - uses: gradle/actions@v4.1.0
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4.4.3
