name: CleanWorkFlow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4.2.1

     - name: Setup Java JDK
       uses: actions/setup-java@v4.4.0
       with:
          distribution: 'temurin'
          java-version: '17'

     - name: Decode Keystore
       env:
         ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
         SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
       run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

     - name: Run Tests with Gradle
       run: ./gradlew test

     - name: Make Gradle executable
       run: chmod +x ./gradlew

     - name: Build Release APK
       env:
         SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
       run: ./gradlew assembleRelease

     - name: Upload a Build Artifact
       env:
         SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
         SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

     - name: Build Release AAb
       run: ./gradlew bundleRelease

     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4.4.3
       with:
          name: release-artifacts
          path: |
             app/build/outputs/apk/release/
             app/build/outputs/bundle/release/
