name: CleanWorkFlow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4.2.1

     - name: Setup Java JDK
       uses: actions/setup-java@v4.4.0
       with:
          distribution: 'temurin'
          java-version: '17'

     - name: Run Tests with Gradle
       run: ./gradlew test

     - name: Make Gradle executable
       run: chmod +x ./gradlew
     - name: Build Release APK
       run: ./gradlew assembleRelease
     - name: Releasing using Hub
       uses: VladDaniliuk/action-release-releaseapk@master
       env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VERSION_VARIABLE: 1.0
          APP_FOLDER: ./app/release/app-release.apk
          RELEASE_TITLE: NewBuild
          NAME_VARIABLE: app-release.apk